name: installing-java
on: [push]
jobs:
  java-job:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: java --version
      - run: echo ${{ github.repository }}
  java-job2:
    runs-on: ubuntu-latest    
    needs: java-job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: java --version
