name: installing-java
on: [push]
jobs:
  java-job:
    runs-on: ubuntu-latest      
    steps:
      - name: GithubActionsRepo
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: java --version
      - run: cat README.md
  java-job2:
    runs-on: ubuntu-latest
    needs: java-job
    steps:
      - name: TestingCheckoutRepo
      - uses: actions/checkout@v2
        with:
          repository: 'WaelLoop/TestingCheckout'
      - run: cat README.md
